function [p_0G]=QRE20_Signal_stage_zero(            p_go_0,...
                                                    p_0GG_1G, p_0GS_1G, p_0SG_1G, p_0SS_1G,...
                                                    p_0GG_1SG_2G, p_0GG_1SS_2G,...
                                                    p_0GS_1SG_2G, p_0GS_1SS_2G,...
                                                    p_0SG_1SG_2G, p_0SG_1SS_2G,...
                                                    p_0SS_1SG_2G, p_0SS_1SS_2G,...
                                                    tau, B2Y, B1Y, a, b)                                                
% Description: 

% Initialize vectors

tol=1e-8;
ksteps=0;
maxsteps=100;
dist=1;
allpha=1/2;

p_0G = p_go_0;

% Core: find QRE

while (ksteps<maxsteps) && (dist>tol)

    piexp_0G=zeros(1,20);
    piexp_0S=zeros(1,20);
    
    for k=1:1:20
     for j=1:1:20
       piexp_0G(1,k) = piexp_0G(1,k) + ... 
                         (1/20)*(...
                                p_0G(j)*...
                                    (...
                                        p_0GG_1G(j)*(...
                                                    p_0GG_1G(k)*B2Y(k)... 
                                                    + (1 - p_0GG_1G(k))*...
                                                                       (...
                                                                       p_0GG_1SG_2G(k)*B2Y(k) + (1-p_0GG_1SG_2G(k))*5 ...
                                                                       )...
                                                    )...
                                       +(1 - p_0GG_1G(j))*(...
                                                    p_0GG_1G(k)*...
                                                                       (...
                                                                        p_0GG_1SG_2G(j)*B2Y(k) + (1-p_0GG_1SG_2G(j))*B1Y(k,a,b)...
                                                                       )...
                                                 + (1 - p_0GG_1G(k))*...
                                                                       (...
                                                                       p_0GG_1SS_2G(j)*...
                                                                                       ( p_0GG_1SS_2G(k)*B2Y(k) + (1 - p_0GG_1SS_2G(k))*5 )... 
                                                                       +(1-p_0GG_1SS_2G(j))*...
                                                                                       ( p_0GG_1SS_2G(k)*B1Y(k,a,b) + (1 - p_0GG_1SS_2G(k))*7 )... 
                                                                       )...            
                                                           )...
                                    )...
                                + (1 - p_0G(j))*...
                                        (...
                                        p_0SG_1G(j)*(...
                                                    p_0GS_1G(k)*B2Y(k)... 
                                                    + (1 - p_0GS_1G(k))*...
                                                                       (...
                                                                       p_0GS_1SG_2G(k)*B2Y(k) + (1-p_0GS_1SG_2G(k))*5 ...
                                                                       )...
                                                    )...
                                       +(1 - p_0SG_1G(j))*(...
                                                    p_0GS_1G(k)*...
                                                                       (...
                                                                        p_0SG_1SG_2G(j)*B2Y(k) + (1-p_0SG_1SG_2G(j))*B1Y(k,a,b)...
                                                                       )...
                                                 + (1 - p_0GS_1G(k))*...
                                                                       (...
                                                                       p_0SG_1SS_2G(j)*...
                                                                                       ( p_0GS_1SS_2G(k)*B2Y(k) + (1 - p_0GS_1SS_2G(k))*5 )... 
                                                                       +(1-p_0SG_1SS_2G(j))*...
                                                                                       ( p_0GS_1SS_2G(k)*B1Y(k,a,b) + (1 - p_0GS_1SS_2G(k))*7 )... 
                                                                       )...            
                                                           )...
                                    )...
                                );                            
       piexp_0S(1,k) = piexp_0S(1,k) + ...       
                              (1/20)*(...
                                p_0G(j)*...
                                    (...
                                        p_0GS_1G(j)*(...
                                                    p_0SG_1G(k)*B2Y(k)... 
                                                    + (1 - p_0SG_1G(k))*...
                                                                       (...
                                                                       p_0SG_1SG_2G(k)*B2Y(k) + (1-p_0SG_1SG_2G(k))*5 ...
                                                                       )...
                                                    )...
                                       +(1 - p_0GS_1G(j))*(...
                                                    p_0SG_1G(k)*...
                                                                       (...
                                                                        p_0GS_1SG_2G(j)*B2Y(k) + (1-p_0GS_1SG_2G(j))*B1Y(k,a,b)...
                                                                       )...
                                                 + (1 - p_0SG_1G(k))*...
                                                                       (...
                                                                       p_0GS_1SS_2G(j)*...
                                                                                       ( p_0SG_1SS_2G(k)*B2Y(k) + (1 - p_0SG_1SS_2G(k))*5 )... 
                                                                       +(1-p_0GS_1SS_2G(j))*...
                                                                                       ( p_0SG_1SS_2G(k)*B1Y(k,a,b) + (1 - p_0SG_1SS_2G(k))*7 )... 
                                                                       )...            
                                                           )...
                                    )...
                                + (1 - p_0G(j))*...
                                        (...
                                        p_0SS_1G(j)*(...
                                                    p_0SS_1G(k)*B2Y(k)... 
                                                    + (1 - p_0SS_1G(k))*...
                                                                       (...
                                                                       p_0SS_1SG_2G(k)*B2Y(k) + (1-p_0SS_1SG_2G(k))*5 ...
                                                                       )...
                                                    )...
                                       +(1 - p_0SS_1G(j))*(...
                                                    p_0SS_1G(k)*...
                                                                       (...
                                                                        p_0SS_1SG_2G(j)*B2Y(k) + (1-p_0SS_1SG_2G(j))*B1Y(k,a,b)...
                                                                       )...
                                                 + (1 - p_0SS_1G(k))*...
                                                                       (...
                                                                       p_0SS_1SS_2G(j)*...
                                                                                       ( p_0SS_1SS_2G(k)*B2Y(k) + (1 - p_0SS_1SS_2G(k))*5 )... 
                                                                       +(1-p_0SS_1SS_2G(j))*...
                                                                                       ( p_0SS_1SS_2G(k)*B1Y(k,a,b) + (1 - p_0SS_1SS_2G(k))*7 )... 
                                                                       )...            
                                                           )...
                                    )...
                                );   
     end;
    end;   
    
    for i=1:1:20
        phat(1,i) = exp(tau*piexp_0G(1,i))/(exp(tau*piexp_0G(1,i)) + exp(tau*piexp_0S(1,i)));
    end;
        
    dist = max(abs(phat-p_0G));

    p_0G=allpha*p_0G+(1-allpha)*phat;
    
    ksteps=ksteps+1;

end


